version: '3.1'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: runner_db
    ports:
      - "5432:5432"
  backend:
    build: .  # Путь к Dockerfile вашего бэкенда
    container_name: backend-app
    ports:
      - "8081:8080"  # Бэкенд будет доступен на порту 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/runner_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
    depends_on:
      - postgres
